<?php

// use App\Livewire\Crud;

use App\Livewire\Crud;
use App\Livewire\Login\Form;
// use App\Livewire\Register;
// use App\Livewire\Register\Navbar;
use Illuminate\Support\Facades\Route;
use Livewire\Volt\Volt;
use App\Livewire\Register\ConductResearch;
use App\Livewire\Register\ConnectionResearcher;
use App\Livewire\Research\Addresearch;
use App\Livewire\Research\Secondformadd;
use App\Livewire\Research\Question;
use App\Http\Controllers\Auth\AddResearchController;
use App\Livewire\Auth\Conduct;
use App\Livewire\Auth\Login;
use App\Livewire\Auth\Register;
use App\Livewire\Home;
use App\Livewire\Homepage\Search;
use App\Livewire\Logout;
use App\Livewire\OtherUserProfile\Follower;
use App\Livewire\OtherUserProfile\Profiles;
use App\Livewire\OtherUserProfile\Stat;
use App\Livewire\Researcher\Research;
use App\Livewire\UserProfile\Profile;
use App\Livewire\Research\Iterms;
use App\Livewire\Researcher\Detail\Bodys;
use App\Livewire\Researcher\Detail\Reference;
use App\Livewire\UserProfile\UserProfilePage;
use App\Livewire\UserProfileStateFollow\Follow;
use App\Livewire\UserProfileStateFollow\State;
use App\Models\User;

Route::get('/', Search::class)->name('nonLogin');
Route::get('/login', Login::class)->name('login');
Route::get('/conduct', Conduct::class)->name('conduct');
Route::get('/register', Register::class)->name('register');
Route::get('/logout', Logout::class)->name('logout');
Route::get('/register/{user_id}', Register::class)->name('register_with_user_id');
// Route::get('/addresearch',Addresearch::class)->name('addresearch'); 
// Route::get('/question', Question::class)->name('question');
Route::get('/profile', Profile::class)->name('profile');
Route::get('/items', Iterms::class)->name('items');
Route::get('/research', Addresearch::class)->name('research');
Route::get('/question', Question::class)->name('question');
Route::get('/research/details/{researchId}',Secondformadd::class)->name('research.secondform');
Route::get('/profile', Profile::class)->name('profile');
Route::get('/follow', Follow::class)->name('follow');
Route::get('/stat', State::class)->name('stat');
Route::get('/home', Home::class)->name('home');
Route::get('/profile/{user}', Profiles::class)->name('user-profile'); 
Route::get('/profile/{user}/stat', Stat::class)->name('user-stat');
Route::get('/profile/{user}/research', Research::class)->name('user-research');
Route::get('/profile/{user}/follower', Follower::class)->name('user-follower');
Route::get('/detailPage/{id}', Bodys::class)->name('detailPage')->where('id', '[0-9]+');
